spack:
  include:
    - https://github.com/tuxfan/spack-env/blob/develop/configs/gnu-default
  specs: [cmake, cgdb, git, caliper, libristra, exodusii, flecsi+graphviz++kokkos++hdf5+flog caliper_detail=medium ^legion conduit=mpi network=gasnet]
  view: true
  concretizer:
    unify: true
  repos:
    - /home/bergen/devel/gitlab/flecsi/2/spack-repo
