packages:
  all:
    require: '%gcc@9.4.0'
    providers:
      mpi: [mpich]
  mpich:
    require: "@3.4.3"
  openmpi:
    require: "@4.1.2"
  cgdb:
    require: "@master"
  caliper:
    require: "@master"
  legion:
    require: "@ctrl-rep-15"
